# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: fantasy_euro_football_development

test:
  <<: *default
  database: fantasy_euro_football_test

production:
  <<: *default
  database: fantasy_euro_football_production
  username: fantasy_football
  password: <%= ENV['FANTASY_FOOTBALL_DATABASE_PASSWORD'] %>
